// benchmarks/weather-app/vue/src/components/WeatherContent.vue
<script setup>
import CurrentWeather from './CurrentWeather.vue';
import Forecast from './Forecast.vue';

defineProps({
	isVisible: { type: Boolean, required: true },
	weatherData: { type: Object, default: null },
});
</script>

<template>
	<div class="weather-content" data-testid="weather-content" :hidden="!isVisible">
		<div class="weather-layout">
			<CurrentWeather v-if="weatherData" :weather-data="weatherData" />
			<Forecast v-if="weatherData" :weather-data="weatherData" />
		</div>
	</div>
</template>

// benchmarks/weather-app/svelte/src/components/WeatherContent.svelte
<script>
	import CurrentWeather from './CurrentWeather.svelte';
	import Forecast from './Forecast.svelte';

	let { isVisible = false, weatherData = null } = $props();
</script>

<div class="weather-content" data-testid="weather-content" hidden={!isVisible}>
	<div class="weather-layout">
		<CurrentWeather {weatherData} />
		<Forecast {weatherData} />
	</div>
</div>
