// benchmarks/weather-app/solid/src/components/Forecast.jsx
import { createEffect, createSignal, For, Show } from 'solid-js';
import ForecastItem from './ForecastItem.jsx';

function Forecast(props) {
	const [activeForecastIndex, setActiveForecastIndex] = createSignal(null);

	const handleToggleForecast = (index) => {
		setActiveForecastIndex((currentIndex) => (currentIndex === index ? null : index));
	};

	createEffect(activeForecastIndex, (activeIndex) => {
		if (activeIndex === null) return undefined;

		const timer = setTimeout(() => {
			const activeElement = document.querySelector('.forecast-item.active');
			activeElement?.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
		}, 100);
		return () => clearTimeout(timer);
	});

	return (
		<Show when={props.weatherData}>
			<section class="forecast-section">
				<h2 class="section-title">7-Day Forecast</h2>
				<div class="forecast">
					<div class="forecast__list" data-testid="forecast-list">
						<For each={props.weatherData.daily.time}>
							{(_date, index) => (
								<ForecastItem
									daily={props.weatherData.daily}
									index={index()}
									isActive={activeForecastIndex() === index()}
									onToggle={handleToggleForecast}
								/>
							)}
						</For>
					</div>
				</div>
			</section>
		</Show>
	);
}

export default Forecast;

// benchmarks/weather-app/react/src/components/Forecast.jsx
import React, { useState, useEffect, useCallback } from 'react';
import ForecastItem from './ForecastItem';

const Forecast = ({ weatherData }) => {
	const [activeForecastIndex, setActiveForecastIndex] = useState(null);

	const handleToggleForecast = useCallback((index) => {
		setActiveForecastIndex((currentIndex) => (currentIndex === index ? null : index));
	}, []);

	useEffect(() => {
		if (activeForecastIndex === null) return undefined;

		const timer = setTimeout(() => {
			const activeElement = document.querySelector('.forecast-item.active');
			if (activeElement) {
				activeElement.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
			}
		}, 100);

		return () => clearTimeout(timer);
	}, [activeForecastIndex]);

	if (!weatherData) {
		return null;
	}

	const { daily } = weatherData;

	return (
		<section className="forecast-section">
			<h2 className="section-title">7-Day Forecast</h2>
			<div className="forecast">
				<div className="forecast__list" data-testid="forecast-list">
					{daily.time.map((date, index) => (
						<ForecastItem
							key={date}
							daily={daily}
							index={index}
							isActive={activeForecastIndex === index}
							onToggle={handleToggleForecast}
						/>
					))}
				</div>
			</div>
		</section>
	);
};

export default Forecast;
