// benchmarks/weather-app/svelte/src/components/SearchForm.svelte
<script>
	import { onMount } from 'svelte';

	let { onSearch, isLoading = false } = $props();
	let inputValue = $state('');

	onMount(() => {
		try {
			inputValue = localStorage.getItem('weather-app-location') || 'London';
		} catch (storageError) {
			console.warn('Could not load saved location:', storageError);
			inputValue = 'London';
		}
	});

	function handleSubmit(event) {
		event.preventDefault();
		const city = inputValue.trim();
		if (!city) return;
		void onSearch(city);
	}
</script>

<section class="search-section">
	<form class="search-form" data-testid="search-form" onsubmit={handleSubmit}>
		<div class="search-form__group">
			<label for="location-input" class="sr-only">Enter city name</label>
			<input
				bind:value={inputValue}
				type="text"
				id="location-input"
				class="search-input"
				placeholder="Enter city name..."
				data-testid="search-input"
				autocomplete="off"
			/>
			<button type="submit" class="search-button" data-testid="search-button" disabled={isLoading}>
				<span class="search-button__text">{isLoading ? 'Loading...' : 'Get Weather'}</span>
				<span class="search-button__icon">🌦️</span>
			</button>
		</div>
	</form>
</section>

// benchmarks/weather-app/react/src/components/SearchForm.jsx
import React, { useRef, useEffect, useCallback } from 'react';

const SearchForm = ({ onSearch, isLoading }) => {
	const inputRef = useRef(null);

	useEffect(() => {
		// Set initial value from localStorage
		const savedLocation = localStorage.getItem('weather-app-location');
		if (savedLocation && inputRef.current) {
			inputRef.current.value = savedLocation;
		} else if (inputRef.current) {
			inputRef.current.value = 'London';
		}
	}, []);

	const handleSubmit = useCallback(
		(e) => {
			e.preventDefault();
			const city = inputRef.current?.value?.trim();

			if (!city) {
				return;
			}

			onSearch(city);
		},
		[onSearch],
	);

	return (
		<section className="search-section">
			<form className="search-form" data-testid="search-form" onSubmit={handleSubmit}>
				<div className="search-form__group">
					<label htmlFor="location-input" className="sr-only">
						Enter city name
					</label>
					<input
						type="text"
						id="location-input"
						className="search-input"
						placeholder="Enter city name..."
						data-testid="search-input"
						autoComplete="off"
						ref={inputRef}
					/>
					<button
						type="submit"
						className="search-button"
						data-testid="search-button"
						disabled={isLoading}
					>
						<span className="search-button__text">{isLoading ? 'Loading...' : 'Get Weather'}</span>
						<span className="search-button__icon">🌦️</span>
					</button>
				</div>
			</form>
		</section>
	);
};

export default React.memo(SearchForm);
