// benchmarks/news/preact/src/runtime-stress/entry.jsx
import { createElement, render } from 'preact';
import { installRuntimeStress } from '../../../../runtime-stress/shared.js';
import { App } from './App.jsx';

const container = document.getElementById('app');
if (!container) throw new Error('Missing runtime stress benchmark root');

const stress = installRuntimeStress();
render(createElement(App), container);
stress.ready = true;

// benchmarks/news/solid/src/runtime-stress/entry.jsx
import { render } from '@solidjs/web';
import { flush } from 'solid-js';
import { installRuntimeStress } from '../../../../runtime-stress/shared.js';
import { App } from './App.jsx';

const container = document.getElementById('app');
if (!container) throw new Error('Missing runtime stress benchmark root');

const stress = installRuntimeStress();
render(() => <App />, container);
flush();
stress.ready = true;
