// benchmarks/news/react/src/runtime-stress/entry.tsx
import { createElement } from 'react';
import { flushSync } from 'react-dom';
import { createRoot } from 'react-dom/client';
import { installRuntimeStress } from '../../../../runtime-stress/shared.js';
import { App } from './App';

const container = document.getElementById('app');
if (!container) throw new Error('Missing runtime stress benchmark root');

const stress = installRuntimeStress();
const root = createRoot(container);
flushSync(() => root.render(createElement(App)));
stress.ready = true;

// benchmarks/news/solid/src/runtime-stress/entry.jsx
import { render } from '@solidjs/web';
import { flush } from 'solid-js';
import { installRuntimeStress } from '../../../../runtime-stress/shared.js';
import { App } from './App.jsx';

const container = document.getElementById('app');
if (!container) throw new Error('Missing runtime stress benchmark root');

const stress = installRuntimeStress();
render(() => <App />, container);
flush();
stress.ready = true;
