// benchmarks/news/solid/src/store-selector-fanout/entry.jsx
import { render } from '@solidjs/web';
import { flush } from 'solid-js';
import { installStoreSelectorStress } from '../../../../store-selector-fanout/shared.js';
import { App } from './App.jsx';

const container = document.getElementById('app');
if (!container) throw new Error('Missing store selector benchmark root');

const stress = installStoreSelectorStress();
stress.flush = (run) => {
	run();
	flush();
};
render(() => <App />, container);
flush();
stress.ready = true;

// benchmarks/news/react/src/store-selector-fanout/entry.tsx
import { createElement } from 'react';
import { flushSync } from 'react-dom';
import { createRoot } from 'react-dom/client';
import { installStoreSelectorStress } from '../../../../store-selector-fanout/shared.js';
import { App } from './App';

const container = document.getElementById('app');
if (!container) throw new Error('Missing store selector benchmark root');

const stress = installStoreSelectorStress();
stress.flush = (run: () => void) => flushSync(run);
const root = createRoot(container);
flushSync(() => root.render(createElement(App)));
stress.ready = true;
